language: go

go:
  - 1.5

script:
  - make test
  - make build
  - ./tplate -version
  - ./tplate -help
  - ./tplate -env
  - ./tplate -list
  - ./tplate fixture/hello
  - ./tplate fixture/foo/var1
  - ./tplate fixture/foo/var2
