language: go

go:
  - 1.5

env:
  global:
    - TPLATE_PATH=$HOME/fixture
    - TPLATE_AUTHOR=travis
    - TPLATE_AUTHOR_EMAIL=travis@example.tld

script:
  - make test
  - make build
  - ./tplate -version
  - ./tplate -help
  - ./tplate -env
  - ./tplate -list
  - ./tplate hello
  - ./tplate foo/var1
  - ./tplate foo/var2
