language: go

go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x

env:
  global:
    - TPLATE_PATH=$TRAVIS_BUILD_DIR/fixture
    - TPLATE_AUTHOR=travis
    - TPLATE_AUTHOR_EMAIL=travis@example.tld

script:
  - make test
  - make build
  - ./tplate -version
  - ./tplate -help
  - ./tplate -env
  - ./tplate -list
  - ./tplate hello
  - ./tplate foo/var1 Foo=123
  - ./tplate foo/var2 Foo=123 Bar=456
